language: python

sudo: required
dist: xenial

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"


# command to install dependencies
install:
  - sudo apt-get update
  - pip --version
  - pip install -e .
  - pip install antlr4-python3-runtime

# command to run tests
script:
  - make check
