#!/usr/bin/env python

import sys

from antlr4 import *
from code.PLambdaLexer import PLambdaLexer
from code.PLambdaParser import PLambdaParser
#from code.PLambdaVisitor import PLambdaVisitor
from code.Visitor import Visitor


def main(argv):
    input = FileStream(argv[1])
    lexer = PLambdaLexer(input)
    stream = CommonTokenStream(lexer)
    parser = PLambdaParser(stream)
    tree = parser.unit()
    visitor = Visitor()
    visitor.visit(tree)

    
if __name__ == '__main__':
    main(sys.argv)