#!/usr/bin/env python

import sys

from antlr4 import *

from code.PLambdaLexer import PLambdaLexer

from code.PLambdaParser import PLambdaParser

from code.Visitor import Visitor


def main(argv):
    filename = argv[1]
    input = FileStream(filename)
    lexer = PLambdaLexer(input)
    stream = CommonTokenStream(lexer)
    parser = PLambdaParser(stream)
    tree = parser.unit()
    visitor = Visitor(filename)
    for c in visitor.visit(tree):
        print c
    return 0
    	  
    
if __name__ == '__main__':
    if len(sys.argv) != 2:
        print 'Usage: {0} <plambda file>'.format(sys.argv[0])
    else:
        sys.exit(main(sys.argv))
