#!/usr/bin/env python

import sys


from src.plambda.PLambda import load

def main(argv):

    codelist = load(argv[1])
    for c in codelist:
        print str(c)
        print repr(c)
    return 0


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print 'Usage: {0} <plambda file>'.format(sys.argv[0])
    else:
        sys.exit(main(sys.argv))
