#!/usr/bin/env python

import sys


from src.plambda.PLambda import rep

def main(argv):
    if len(sys.argv) != 2:
        rep(None)
    else:
        rep(argv[1])
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
