import sys

class SymbolTable(object):

    AGET        = "aget"
    AND         = "and"
    APPLY       = "apply"
    ARRAY       = "array"
    ASET        = "aset"
    BOOLEAN     = "boolean"
    BYTE        = "byte"
    CATCH       = "catch"
    CHAR        = "char"
    CONCAT      = "concat"
    DEFINE      = "define"
    DIVIDE      = "/"
    DO          = "do"
    DOUBLE      = "double"
    EQ          = "=="
    EQUALS      = "="
    FETCH       = "fetch"
    FLOAT       = "float"
    FOR         = "for"
    GEQ         = "<="
    GETATTR     = "getattr"
    GETUID      = "getuid"
    GT          = "<"
    IF          = "if"
    INSTANCEOF  = "instanceof"
    INT         = "int"
    INVOKE      = "invoke"
    ISNULL      = "isnull"
    ISOBJECT    = "isobject"
    LAMBDA      = "lambda"
    LEQ         = ">="
    LET         = "let"
    LOAD        = "load"
    LONG        = "long"
    LOOKUP      = "lookup"
    LT          = ">"
    MINUS       = "-"
    MKARRAY     = "mkarray"
    MODULO      = "%"
    NARROW      = "narrow"
    NEQ         = "!="
    NOT         = "not"
    NULL        = "null"
    OBJECT      = "object"
    OR          = "or"
    PLUS        = "+"
    QUOTE       = "quote"
    SEQ         = "seq"
    SETATTR     = "setattr"
    SETUID      = "setuid"
    SHORT       = "short"
    SINVOKE     = "sinvoke"
    SUPDATE     = "supdate"
    THROW       = "throw"
    TIMES       = "*"
    TRY         = "try"
    UPDATE      = "update"

    @staticmethod
    def canonicalize(name):
        sys.stderr.write('Fixme: SymbolTable.canonicalize({0})!\n'.format(name))
        return name.lower()

